---------------------------------------------------------------------------------------------------
-- unilib mod by A S Lewis, incorporating materials from many other mods
---------------------------------------------------------------------------------------------------
-- From:    GLEMr6
-- Code:    LGPL 2.1
-- Media:   unknown
---------------------------------------------------------------------------------------------------

unilib.pkg.shared_coral_pillar = {}

local S = unilib.intllib
local mode = unilib.imported_mod_table.glemr6.add_mode

---------------------------------------------------------------------------------------------------
-- Shared variables
---------------------------------------------------------------------------------------------------

unilib.pkg.shared_coral_pillar.node_box_table = {}

-- (The node is drawn with small "pillars" on a 5x5 grid)
local count = 0
local pillars = 5

for x = 1, pillars do

    for z = 1, pillars do

        local d2 = (2 / (pillars + 2)) / (pillars - 1)
        local d1 = (1 + d2) / pillars
        local mini_table = {}

        mini_table[#mini_table + 1] = (x - 1) * d1 - 0.5
        mini_table[#mini_table + 1] = -0.5
        mini_table[#mini_table + 1] = (z - 1) * d1 - 0.5
        mini_table[#mini_table + 1] = x * d1 - d2 - 0.5
        mini_table[#mini_table + 1] = 0.5 - (math.random(1, 4) + math.random(4)) * 0.1
        mini_table[#mini_table + 1] = z * d1 - d2 - 0.5

        count = count + 1
        unilib.pkg.shared_coral_pillar.node_box_table[count] = mini_table

    end

end

---------------------------------------------------------------------------------------------------
-- New code
---------------------------------------------------------------------------------------------------

function unilib.pkg.shared_coral_pillar.init()

    return {
        description = "Shared functions for coral pillars (from GLEMr6)",
        notes = "Nodes partially generated by this package are processor-intensive, and should" ..
                " be used very sparingly",
    }

end
